// Code generated by Slice Machine. DO NOT EDIT.

import Post from './Post';
import Product from './Product';

export {
	Post,
	Product,
};

export const components = {
	post: Post,
	product: Product,
};
